### PR TITLE
Adding support for TCP connections

### PR DESCRIPTION
**Pull request by replay**
This implements TCP connection support. It also makes the client reconnect automatically if the connection dies. When using TCP the client will block until a message is sent successfully.

### CODE REVIEW

**Comment by jsocol** [comment]
This raises a bunch of questions and I'm honestly, as I said in #54, not really excited about adding TCP support.

- How does this affect thread safety? `StatsClient` objects have always been as safe as the `socket.socket().sendto` method is for UDP. Now we have a persistent connection we're potentially sharing across threads.
- This changes the promise of the library, which was "make a reasonable attempt then just power through". Adding `time.sleep()` is, in particular, not something I want to see, as it makes _any_ client method take a potentially _huge_ amount of time.
- The `while True` construct takes a lot of unpacking to understand whether or not it can turn into an infinite loop for UDP sockets. I had to get to the man page for send(2) to verify that.

**Comment by replay** [comment]
Thanks for your quick reply, I'm going to try to find a way that satisfies your three valid concerns:

1) I'll use an object internal `dict()` to keep the sockets, the keys will be the thread's TIDs
2) I will not loop or sleep in the Statsd client. I will rather call `connect()` in `send()` instead of `init()` if the socket is not already connected. If an open connection has died I'll try to reconnect only once on `send()`. If a connect fails due to `connection refused` or `connection timed out` the exception will be raised to be handled by the user, so if the user uses TCP he should wrap the `send()` in a `try: except:`.
3) To improve readability I'll split `_send()` into `_send_udp()` and `_send_tcp()`.

What do you think about these ideas?

**Comment by DanCech** [comment]
To clarify, the reason for adding TCP support here is to support our use-case of pulling messages containing events from an AMQP queue and forward them to statsd with delivery confirmation.  While UDP makes sense for initial collection, when using statsd like this as a component within a larger metric collection system we want the ability to tell whether the metric was received by statsd so that it can be retried if statsd is not available (using AMQP as a buffer).

**Comment by jsocol** [comment]
> I'll use an object internal dict() to keep the sockets, the keys will be the thread's TIDs

Before picking a solution, I want to make sure we're very clear on what the new guarantee is. Personally, I still want `StatsClient` objects to be thread-safe, and assume that `Pipeline` objects will continue to not be. What happens when a thread creates a `Pipeline` from a shared `StatsClient`?

A lot of this complexity is exactly why I am still not yet convinced this is a good idea. Early on there were attempts to do more complex threading management and the whole library got better when they were taken out. How big a win is TCP support vs the code cost?

(I think a `threading.local()` instance would beat an internal `dict()`, if we decide to go this route.)

> I will not loop or sleep in the Statsd client. I will rather call connect() in send() instead of init() if the socket is not already connected. If an open connection has died I'll try to reconnect only once on send(). If a connect() fails due to connection refused or connection timed out the exception will be raised to be handled by the user, so if the user uses TCP he should wrap the send() in a try: except:.

That dramatically changes the contract of the library from "doesn't raise" to "might raise." That's huge.

It's subtle, but this was a very opinionated decision: that it's better for the application to work than for instrumentation to be 100% reliable. An argument can be made that it's the wrong decision, or that it should be left up to the developer, but an implicit switch based on the transport isn't the way to do it. (If anything, an `__init__` kwarg like `fail_silently=True` would be the right way.) Developer A may not know that DevOps B decided to change the transport, and that they now need to try/except every call. Conversely, DevOps B probably didn't audit the code base to catch everything when the network transport requirements changed.

**Comment by jsocol** [comment]
> To clarify, the reason for adding TCP support here is to support our use-case of pulling messages containing events from an AMQP queue and forward them to statsd with delivery confirmation.  While UDP makes sense for initial collection, when using statsd like this as a component within a larger metric collection system we want the ability to tell whether the metric was received by statsd so that it can be retried if statsd is not available (using AMQP as a buffer).

I'm confused. The AMQP queue contains the data that you're sending to statsd?

The official StatsD server supports TCP transport, and that's the only reason I'm even a little open to adding it here, but that means that adding TCP is going to need to be in the most generic way possible, not to fit into any specific use case or changing the promises of this library. The TCP transport seems to exist mostly to get reliable metrics over unreliable networks, but that's just relying on TCP, not doing it at the application layer.

**Comment by DanCech** [comment]
Absolutely, we're not talking about changing the library to do anything except add vanilla support for TCP.  We completely understand your concerns and agree 100% that support for TCP should not in any case involve changes to the way the library is used or add significant complexity.

The point of my original post was just to explain our use-case for TCP, where the code *using* the library needs to be able to confirm whether the metric was received by statsd.

Some more background might make things clearer.  We have various systems that produce metrics and send them to local collectors via UDP.  Those metrics are then passed to a rabbitmq exchange, from which they are consumed by our worker process which sends them to statsd (hopefully using pystatsd) for ingestion into graphite, as well as by other consumers.  If statsd isn't available we would like to have pystatsd let us know that the transmission failed so we can NACK the message back to rabbitmq and it can be retried, something we can't do via UDP.

**Comment by jsocol** [comment]
I need to let this ferment a little. Writing out an answer I got to a point that scared me, introducing a colossal footgun.

**Comment by DanCech** [comment]
No worries, looking forward to hearing your feedback.  We are assuming there are other potential users of pystatsd who could find applications for a TCP transport, which is why we'd like to contribute back if we can.  Should it not be a fit we can always write a custom statsd client for our needs and maintain it in-house.  In the meantime we'll go ahead with work on a patch that addresses the points you brought up earlier and we can see where things end up.

**Comment by replay** [comment]
I've updated the patch to hopefully address all your concerns above.  To keep things clean it turned into a larger patch than originally intended, but I think this way it is still relatively easy to read and it is extendable because the connection handling for each protocol is isolated from the others.  

* The StatsClient is still thread safe because the tcp connection socket is kept in a `threading.local` object.
* The Pipeline should also be fine and still work the same way
* By default `fail_silently` is `True` so the behavior of the old version doesn't change unless the user passes `fail_silently=False`.
* There are no loops or waits anymore. It only tries to reconnect once if a connection has once been established, but has died in the meantime. If this reconnect fails it will swallow the error by default or raise an exception if `fail_silently=False`. Basically this means that whenever `send()` gets called on an instance that has `fail_silently` off, it should be wrapped in a `try-except` to catch `socket.error`s.

I have not yet updated the tests or the docs yet, but if the patch itself looks acceptable I can go ahead and do that also.  Look forward to hearing your feedback.

**Comment by jsocol** [comment]
OK, I think I've finally got a handle on the underlying issue I have here.

The thing that was bugging me was `proto='tcp', fail_silently=True`. It's dangerous, or requires that `fail_silently` doesn't do what it says on the tin.

The root of the problem is: UDP clients are stateless(/connectionless), and TCP clients would be stateful(/connection-mode). That manifests in a couple of big ways:

- Errors. UDP clients just can't raise very many. It doesn't matter what `fail_silently` says: you will never get a exception from the vast majority of things that can go wrong. UDP clients don't even care if the target exists, let alone if they can connect to it.
- Thread safety. Since the underlying connection is stateless, UDP clients are trivially thread-safe. The only thread-unsafe part of the Pipeline is storing the unsent data, the actual sending could be safely interleaved with another thread without a problem.

I started out with the position that changing the underlying transport shouldn't change the application semantics, but what I come around to is: that's nonsense. It literally doesn't make sense. But I still think that changing _just_ the transport shouldn't. Changing one kwarg, especially for the default clients, shouldn't require re-working how an application uses the client.

So what I'm coming around to is: it should be possible, but harder. Supporting TCP does belong in this library, but not in the same object.

What do you think about a `TCPStatsClient` (or a better name) class? It can probably subclass the current `StatsClient` class—I think there are plenty of hooks already to support Pipelines, judging from the existing code here.

This would allow a bunch of things:

- `StatsClient` is thread safe, but `TCPStatsClient` is not (much like Pipelines). This avoids having to hide stateful connections in threadlocals. Applications can still create threadlocal clients if they need to.
- `StatsClient` swallows the basically zero errors it can produce, but `TCPStatsClient` does not, and makes the application decide what to do. That way we don't have to do any hidden retries, and we respect the spirit of the "reliable transport" idea.
- `TCPStatsClient` can expose `reconnect` and `close` methods that don't make sense for `StatsClient`.
- `TCPStatsClient` can have additional constructor kwargs that don't make sense or are unnecessary for `StatsClient`, like `timeout`, and `debug` (I've always maintained it's unnecessary for the UDP client: since you're already changing constructor args, just point it at localhost. But for a TCP client, skipping the connection and actual sending matters). It could even drop `maxudpsize` and just rely on `sendall` for Pipelines (eventually, it would require a little refactoring).
- Opting for TCP is possible but a bigger choice. It makes more sense to have different application semantics when you're creating an entirely different kind of object.

I don't really imagine having `TCPStatsClient` instances in the `statsd.defaults` modules. Those are intended for super-common cases, but anything else—including TCP—is expected to create its own client.

Sorry I've been a little slow on this one. I had to write like 4 or 5 answers before I actually figured out what I was getting at.

**Comment by replay** [comment]
Ok, we think your reasoning makes sense, so we gave it another try in a new branch. 

I created a new pull request from it: #59

**Pull request closed without merging**
