### PR TITLE
Updated statsd client to allow less than 1 ms timing

### PR DESCRIPTION
**Pull request by jstasiak**
This is a version of https://github.com/jsocol/pystatsd/pull/63 changed to include code review feedback.

### CODE REVIEW

**Comment by scbunn** [comment]
This looks good to me

**Comment by jsocol** [comment]
Thanks, folks!

**Comment by jsocol** [comment]
Pushed 3.2 up to PyPI just now

**Comment by jstasiak** [comment]
Thank you @scbunn and @jsocol!

**Pull request merged**
