### PR TITLE
Fix UnicodeDecodeError on utf-8 stat names

### PR DESCRIPTION
**Pull request by haron**

### CODE REVIEW

**Comment by jsocol** [comment]
Is this a new bug in 3.2, or has it been around for a while? It would need tests, and I'm not sure that `'ignore'` is actually the correct behavior. How does [statsd itself](https://github.com/etsy/statsd/) handle non-ascii keys?

**Comment by haron** [comment]
This is not a new bug. From my point of view, ignoring (deleting, actually) non-ascii characters is better than failing with UnicodeDecodeError. Statsd and Graphite do handle utf-8 keys as well as ascii, but I'm not sure that utf-8 keys are supported by other tools, like Graphite dashboards.

**Comment by jsocol** [comment]
I disagree, I don't think it's appropriate to transparently change what you put in the key from what it sends to statsd, it violates the idea of least surprise. Especially because for non-Roman languages, we'd end up dropping the entire metric name:

```python
>>> s = u'ру́сский'
>>> s.encode('ascii', 'ignore')
''
```

It also looks like Graphite [does not support utf-8 yet](https://github.com/graphite-project/graphite-web/issues/243), so I think this behavior is correct for now. If the whole stack starts supporting Unicode, then we can changes this to `.encode('utf-8')`.

**Comment by haron** [comment]
Ok, no problem. (Graphite itself works well with utf-8 keys, but  graphite-web lacks the support)

**Comment by jsocol** [comment]
If graphite-web adds support and we can verify that the statsd server won't have a problem with it, then a solution is more complicated, especially with Pipelines. It begins with something like:

```python
if isinstance(data, string_type):
    data = data.encode('utf-8')
```

I'd rather not make `six` a dependency, for just this, so we'd need to define `string_type` as either `unicode` in Py2 or `str` in Py3.

For Pipelines, we need to keep the length of the encoded bytes, not the string, under maxudpsize, which means encoding before doing the length calculations.

And all of this will of course need tests.

**Pull request closed without merging**
